#pragma once


// Split keyboard configurations
#define SPLIT_USB_DETECT
#define SPLIT_TRANSPORT_MIRROR
#define SPLIT_LAYER_STATE_ENABLE
#define SPLIT_LED_STATE_ENABLE
#define SPLIT_MODS_ENABLE


// `Serial` driver configuration
#define SERIAL_USART_TX_PIN GP28
#define SERIAL_USART_RX_PIN GP27
#define SERIAL_USART_FULL_DUPLEX
//#define SERIAL_PIO_USE_PIO1
//#define SOFT_SERIAL_PIN GP28			// Must be same as SERIAL_USART_TX_PIN

// RP2040 double tap reset
#define RP2040_BOOTLOADER_DOUBLE_TAP_RESET
#define RP2040_BOOTLOADER_DOUBLE_TAP_RESET_TIMEOUT 500U

#define RGB_DI_PIN GP21
#define RGB_MATRIX_LED_COUNT 54
#define RGB_MATRIX_SPLIT { 27, 27 }

//#define WS2812_DRIVER pwm
//#define WS2812_PWM_DRIVER PWMD2
//#define WS2812_PWM_CHANNEL 1
//#define WS2812_PWM_PAL_MODE 2
//#define WS2812_DMA_STREAM STM32_DMA1_STREAM2
//#define WS2812_DMA_CHANNEL 2

/*
// RGB matrix configs
#ifdef RGB_MATRIX_ENABLE
#	define RGB_DI_PIN GP15
#	define RGBLED_NUM 76
#	define DRIVER_LED_TOTAL 76
#	define RGB_MATRIX_SPLIT { 38, 38 }				// Number of LEDs in each half

#	define RGB_MATRIX_MAXIMUM_BRIGHTNESS 100
#	define RGB_MATRIX_STARTUP_HUE 80
#	define RGB_MATRIX_FRAMEBUFFER_EFFECTS
#	define RGB_MATRIX_KEYPRESSES

#	define ENABLE_RGB_MATRIX_BREATHING
#	define ENABLE_RGB_MATRIX_GRADIENT_UP_DOWN
#	define ENABLE_RGB_MATRIX_GRADIENT_LEFT_RIGHT
#	define ENABLE_RGB_MATRIX_CYCLE_ALL
#	define ENABLE_RGB_MATRIX_CYCLE_LEFT_RIGHT
#	define ENABLE_RGB_MATRIX_CYCLE_UP_DOWN
#	define ENABLE_RGB_MATRIX_RAINBOW_MOVING_CHEVRON
#	define ENABLE_RGB_MATRIX_CYCLE_OUT_IN
#	define ENABLE_RGB_MATRIX_CYCLE_OUT_IN_DUAL
#	define ENABLE_RGB_MATRIX_CYCLE_PINWHEEL
#	define ENABLE_RGB_MATRIX_CYCLE_SPIRAL
#	define ENABLE_RGB_MATlRIX_DUAL_BEACON
#	define ENABLE_RGB_MATRIX_RAINBOW_BEACON
#	define ENABLE_RGB_MATRIX_RAINBOW_PINWHEELS
#	define ENABLE_RGB_MATRIX_SOLID_REACTIVE_SIMPLE
#	define ENABLE_RGB_MATRIX_SOLID_REACTIVE
#	define ENABLE_RGB_MATRIX_SOLID_REACTIVE_WIDE
#	define ENABLE_RGB_MATRIX_SOLID_REACTIVE_MULTIWIDE
#	define ENABLE_RGB_MATRIX_SOLID_REACTIVE_CROSS
#	define ENABLE_RGB_MATRIX_SOLID_REACTIVE_MULTICROSS
#	define ENABLE_RGB_MATRIX_SOLID_REACTIVE_NEXUS
#	define ENABLE_RGB_MATRIX_SOLID_REACTIVE_MULTINEXUS
#	define ENABLE_RGB_MATRIX_SPLASH
#	define ENABLE_RGB_MATRIX_MULTISPLASH
#	define ENABLE_RGB_MATRIX_SOLID_SPLASH
#	define ENABLE_RGB_MATRIX_SOLID_MULTISPLASH
#endif
*/